"use client";

import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, Trash2 } from "lucide-react";
import { useCart } from "./cart-provider";
import { formatCurrency } from "@/lib/format";

export function CartPageContent() { const { items, subtotal, updateQuantity, removeItem } = useCart(); if (!items.length) return <div className="grid min-h-[45vh] place-content-center text-center"><h2 className="display text-4xl">Tu carrito está vacío</h2><p className="muted mt-3">Tu próxima pieza favorita te espera.</p><Link href="/tienda" className="button-primary mx-auto mt-7">Explorar tienda</Link></div>; return <div className="grid gap-10 lg:grid-cols-[1fr_360px]"><div className="space-y-5">{items.map((item) => <article key={item.key} className="grid grid-cols-[100px_1fr] gap-4 border-b hairline pb-5 md:grid-cols-[130px_1fr_auto]"><div className="relative aspect-[3/4] overflow-hidden bg-white">{item.image && <Image src={item.image} alt={item.name} fill sizes="130px" className="object-cover object-top"/>}</div><div><Link href={`/producto/${item.slug}`} className="font-semibold">{item.name}</Link>{(item.color || item.size) && <p className="muted mt-1 text-sm">{[item.color,item.size].filter(Boolean).join(" · ")}</p>}<p className="mt-3 text-sm">{formatCurrency(item.price)}</p><div className="mt-4 inline-flex items-center border hairline"><button className="p-2" onClick={() => updateQuantity(item.key,item.quantity-1)} aria-label="Reducir"><Minus size={15}/></button><span className="min-w-9 text-center text-sm">{item.quantity}</span><button className="p-2" onClick={() => updateQuantity(item.key,item.quantity+1)} disabled={item.quantity>=item.maxStock} aria-label="Aumentar"><Plus size={15}/></button></div></div><button className="self-start p-2" onClick={() => removeItem(item.key)} aria-label={`Eliminar ${item.name}`}><Trash2 size={18}/></button></article>)}</div><aside className="h-fit border border-[var(--line)] bg-[var(--paper)] p-6 lg:sticky lg:top-28"><h2 className="display text-3xl">Resumen</h2><div className="my-5 flex justify-between border-y hairline py-5"><span>Subtotal</span><strong>{formatCurrency(subtotal)}</strong></div><p className="muted text-xs leading-5">El envío y la forma de pago se confirman personalmente por WhatsApp.</p><Link href="/checkout" className="button-primary mt-6 w-full">Finalizar pedido</Link></aside></div>; }
