"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { checkoutSchema } from "@/lib/validation";
import { useCart } from "./cart-provider";
import { formatCurrency } from "@/lib/format";
import { z } from "zod";

type Fields = Omit<z.input<typeof checkoutSchema>, "items">;
type OrderResponse = { id: string; orderNumber: string; subtotal: number; whatsapp: string; items: { product_name_snapshot: string; variant_snapshot: { size?: string; color?: string }; quantity: number; unit_price: number; subtotal: number }[]; error?: string };

export function CheckoutForm() {
  const { items, subtotal, clear } = useCart(); const router = useRouter(); const [serverError, setServerError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const { register, handleSubmit, formState: { errors } } = useForm<Fields>({ resolver: zodResolver(checkoutSchema.omit({ items: true })), defaultValues: { deliveryMethod: "Envío a domicilio", notes: "" } });
  const submit = handleSubmit(async (values) => {
    setServerError(""); setSubmitting(true); const popup = window.open("about:blank", "_blank");
    try { const response = await fetch("/api/orders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, items: items.map((item) => ({ productId: item.productId, variantId: item.variantId, quantity: item.quantity })) }) }); const data = await response.json() as OrderResponse; if (!response.ok) throw new Error(data.error ?? "No pudimos crear el pedido.");
      const productLines = data.items.map((item) => { const options = [item.variant_snapshot?.size && `Talla: ${item.variant_snapshot.size}`, item.variant_snapshot?.color && `Color: ${item.variant_snapshot.color}`].filter(Boolean); return `${item.quantity} x ${item.product_name_snapshot}${options.length ? `\n${options.join(" · ")}` : ""}\n${formatCurrency(item.subtotal)}`; }).join("\n\n");
      const message = `Hola MJ Vault, quiero realizar el pedido #${data.orderNumber}.\n\nPRODUCTOS\n\n${productLines}\n\nSubtotal: ${formatCurrency(data.subtotal)}\n\nDATOS\n\nNombre: ${values.customerName}\nTeléfono: ${values.phone}\nCiudad: ${values.city}, ${values.department}\nDirección: ${values.address}\nBarrio: ${values.neighborhood}\nEntrega: ${values.deliveryMethod}${values.notes ? `\nInformación adicional: ${values.notes}` : ""}\n\nQuedo pendiente para confirmar disponibilidad, envío y forma de pago.`;
      const url = `https://wa.me/${data.whatsapp}?text=${encodeURIComponent(message)}`; if (popup) popup.location.replace(url); else window.location.assign(url); clear(); router.push(`/checkout/exito?pedido=${encodeURIComponent(data.orderNumber)}`);
    } catch (error) { popup?.close(); setServerError(error instanceof Error ? error.message : "No pudimos crear el pedido."); } finally { setSubmitting(false); }
  });
  if (!items.length) return <div className="border-y hairline py-16 text-center"><h2 className="display text-4xl">No hay productos para finalizar</h2><button className="button-primary mt-6" onClick={() => router.push("/tienda")}>Ir a la tienda</button></div>;
  const fieldError = (name: keyof Fields) => errors[name] ? <span className="text-xs text-[var(--danger)]">Revisa este campo.</span> : null;
  return <form onSubmit={submit} className="grid gap-10 lg:grid-cols-[1fr_380px]"><section className="grid gap-5"><div className="grid gap-5 md:grid-cols-2"><div className="field md:col-span-2"><label htmlFor="customerName">Nombre completo</label><input id="customerName" className="input" autoComplete="name" {...register("customerName")}/>{fieldError("customerName")}</div><div className="field"><label htmlFor="phone">Teléfono</label><input id="phone" className="input" inputMode="tel" autoComplete="tel" {...register("phone")}/>{fieldError("phone")}</div><div className="field"><label htmlFor="department">Departamento</label><input id="department" className="input" autoComplete="address-level1" {...register("department")}/>{fieldError("department")}</div><div className="field"><label htmlFor="city">Ciudad</label><input id="city" className="input" autoComplete="address-level2" {...register("city")}/>{fieldError("city")}</div><div className="field"><label htmlFor="neighborhood">Barrio</label><input id="neighborhood" className="input" {...register("neighborhood")}/>{fieldError("neighborhood")}</div><div className="field md:col-span-2"><label htmlFor="address">Dirección</label><input id="address" className="input" autoComplete="street-address" {...register("address")}/>{fieldError("address")}</div><div className="field md:col-span-2"><label htmlFor="deliveryMethod">Método de entrega</label><select id="deliveryMethod" className="input" {...register("deliveryMethod")}><option>Envío a domicilio</option><option>Por acordar con MJ Vault</option></select></div><div className="field md:col-span-2"><label htmlFor="notes">Información adicional</label><textarea id="notes" className="input" placeholder="Indicaciones para la entrega, referencias u observaciones" {...register("notes")}/>{fieldError("notes")}</div></div>{serverError && <div role="alert" className="border border-[var(--danger)] bg-red-50 p-4 text-sm text-[var(--danger)]">{serverError}</div>}</section><aside className="h-fit bg-[#171512] p-6 text-white lg:sticky lg:top-28"><p className="eyebrow text-[var(--gold-soft)]">Tu pedido</p><div className="mt-5 space-y-4">{items.map((item) => <div key={item.key} className="flex justify-between gap-4 text-sm"><div><span>{item.quantity} × {item.name}</span>{(item.color || item.size) && <p className="mt-1 text-xs text-white/55">{[item.color,item.size].filter(Boolean).join(" · ")}</p>}</div><span>{formatCurrency(item.price*item.quantity)}</span></div>)}</div><div className="my-6 flex justify-between border-y border-white/20 py-5"><span>Subtotal</span><strong>{formatCurrency(subtotal)}</strong></div><p className="text-xs leading-5 text-white/60">Crearemos tu pedido antes de abrir WhatsApp. Allí confirmaremos envío y forma de pago.</p><button disabled={submitting} className="button-dark mt-6 w-full">{submitting ? "Creando pedido…" : "Continuar en WhatsApp"}</button></aside></form>;
}
