"use client";

import { useMemo, useState } from "react";
import { Minus, Plus, ShoppingBag } from "lucide-react";
import type { Product } from "@/types";
import { useCart } from "./cart-provider";

export function ProductPurchase({ product }: { product: Product }) {
  const variants = useMemo(() => product.variants ?? [], [product.variants]); const colors = [...new Set(variants.map((v) => v.color).filter(Boolean))] as string[]; const sizes = [...new Set(variants.map((v) => v.size).filter(Boolean))] as string[];
  const [color, setColor] = useState(colors.length === 1 ? colors[0] : ""); const [size, setSize] = useState(sizes.length === 1 ? sizes[0] : ""); const [quantity, setQuantity] = useState(1); const { addItem } = useCart();
  const selected = useMemo(() => variants.find((variant) => (!colors.length || variant.color === color) && (!sizes.length || variant.size === size)), [variants, colors.length, sizes.length, color, size]);
  const stock = variants.length ? selected?.stock ?? 0 : product.stock; const selectionComplete = !variants.length || Boolean((!colors.length || color) && (!sizes.length || size)); const soldOut = selectionComplete && stock === 0;
  const add = () => { if (!selectionComplete || stock < 1) return; const image = product.images?.find((entry) => entry.is_primary) ?? product.images?.[0]; addItem({ productId: product.id, variantId: selected?.id ?? null, slug: product.slug, name: product.name, image: image?.image_url ?? null, price: product.price, quantity, size: selected?.size ?? null, color: selected?.color ?? null, maxStock: stock }); };
  return <div className="space-y-6">{colors.length > 0 && <fieldset><legend className="eyebrow mb-3">Color</legend><div className="flex flex-wrap gap-2">{colors.map((value) => <button type="button" key={value} onClick={() => { setColor(value); setQuantity(1); }} className={`min-h-11 border px-4 text-sm ${color === value ? "border-[var(--ink)] bg-[var(--ink)] text-white" : "hairline"}`}>{value}</button>)}</div></fieldset>}{sizes.length > 0 && <fieldset><legend className="eyebrow mb-3">Talla</legend><div className="flex flex-wrap gap-2">{sizes.map((value) => { const unavailable = color ? !variants.some((v) => v.color === color && v.size === value && v.stock > 0) : false; return <button type="button" key={value} onClick={() => { setSize(value); setQuantity(1); }} disabled={unavailable} className={`grid min-h-11 min-w-12 place-items-center border px-3 text-sm ${size === value ? "border-[var(--ink)] bg-[var(--ink)] text-white" : "hairline"}`}>{value}</button>; })}</div></fieldset>}<div>{!selectionComplete ? <p className="text-sm text-[var(--gold)]">Selecciona tus opciones para ver disponibilidad.</p> : soldOut ? <p className="text-sm font-bold text-[var(--danger)]">Agotado</p> : <p className="text-sm text-[var(--success)]">Disponible · {stock} {stock === 1 ? "unidad" : "unidades"}</p>}</div><div className="flex gap-3"><div className="inline-flex items-center border hairline"><button type="button" className="p-3" onClick={() => setQuantity((v) => Math.max(1, v-1))} aria-label="Reducir cantidad"><Minus size={16}/></button><span className="min-w-10 text-center">{quantity}</span><button type="button" className="p-3" onClick={() => setQuantity((v) => Math.min(stock, v+1))} disabled={!stock || quantity >= stock} aria-label="Aumentar cantidad"><Plus size={16}/></button></div><button type="button" onClick={add} disabled={!selectionComplete || soldOut} className="button-primary flex-1"><ShoppingBag size={17}/> {soldOut ? "Agotado" : "Agregar al carrito"}</button></div></div>;
}
