import Image from "next/image";
import Link from "next/link";
import { Headphones, PackageCheck, ShieldCheck, Sparkles } from "lucide-react";
import { getCategories, getProducts, getSettings } from "@/lib/data";
import { ProductGrid } from "@/components/store/product-grid";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const [newProducts, featured, categories, settings] = await Promise.all([getProducts({ isNew: true, limit: 8 }), getProducts({ featured: true, limit: 8 }), getCategories(), getSettings()]);
  const heroImage = settings?.hero_image_url ?? newProducts[0]?.images?.[0]?.image_url ?? "/catalog/rhode-pocket-blush.png";
  return <main><section className="relative min-h-[76svh] overflow-hidden bg-[#171512] text-white"><Image src={heroImage} alt="Selección de MJ Vault" fill priority sizes="100vw" className="object-cover object-top opacity-65" /><div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/30 to-transparent" /><div className="container-page relative flex min-h-[76svh] items-end pb-14 md:items-center md:pb-0"><div className="max-w-2xl"><p className="eyebrow mb-5 text-[var(--gold-soft)]">MJ Vault · Boutique virtual</p><h1 className="display text-6xl leading-[.9] sm:text-7xl md:text-8xl">{settings?.hero_title ?? "Más que moda, tu esencia."}</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/80">{settings?.hero_subtitle ?? "Descubre piezas seleccionadas para expresar tu estilo."}</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button-dark" href="/tienda">Ver colección</Link><Link className="button-secondary border-white text-white hover:bg-white hover:text-black" href="/tienda?new=true">Nuevos ingresos</Link></div></div></div></section>
  <section className="container-page py-16 md:py-24"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow text-[var(--gold)]">Explora</p><h2 className="display mt-2 text-4xl md:text-5xl">Categorías seleccionadas</h2></div><Link href="/tienda" className="hidden text-xs font-bold uppercase tracking-[.14em] md:block">Ver todo</Link></div><div className="grid gap-4 md:grid-cols-2">{(categories.length ? categories.slice(0, 4) : [{ slug: "belleza", name: "Belleza", image_url: "/catalog/rare-beauty-blush.png" }, { slug: "cuidado-personal", name: "Cuidado personal", image_url: "/catalog/eos-mini-body-lotion.png" }]).map((category, index) => <Link href={`/categoria/${category.slug}`} key={category.slug} className="group relative aspect-[16/10] overflow-hidden bg-white"><Image src={category.image_url ?? (index % 2 ? "/catalog/eos-mini-body-lotion.png" : "/catalog/rare-beauty-blush.png")} alt={category.name} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover object-top transition duration-700 group-hover:scale-[1.025]" /><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" /><span className="display absolute bottom-6 left-6 text-4xl text-white">{category.name}</span></Link>)}</div></section>
  <section className="container-page pb-16 md:pb-24"><div className="mb-8"><p className="eyebrow text-[var(--gold)]">Recién llegados</p><h2 className="display mt-2 text-4xl md:text-5xl">Nuevos ingresos</h2><p className="muted mt-3 text-sm">Diseños que llegan para convertirse en tus favoritos.</p></div><ProductGrid products={newProducts} /></section>
  <section className="bg-[#1b1916] text-white"><div className="grid md:grid-cols-2"><div className="relative min-h-[480px]"><Image src="/catalog/rhode-bronzer.png" alt="La colección de MJ Vault" fill sizes="50vw" className="object-cover object-top" /></div><div className="flex items-center px-7 py-16 md:px-16"><div className="max-w-lg"><p className="eyebrow text-[var(--gold-soft)]">La colección</p><h2 className="display mt-4 text-5xl md:text-6xl">Tu estilo. Tu esencia. Tu Vault.</h2><p className="mt-5 leading-7 text-white/65">Una selección cuidada para acompañar la forma única en que eliges verte y sentirte.</p><Link href="/tienda" className="button-dark mt-8">Descubrir colección</Link></div></div></div></section>
  <section className="container-page py-16 md:py-24"><div className="mb-8"><p className="eyebrow text-[var(--gold)]">Selección MJ</p><h2 className="display mt-2 text-4xl md:text-5xl">Productos destacados</h2></div><ProductGrid products={featured} /></section>
  <section className="border-y hairline bg-[var(--paper)]"><div className="container-page grid grid-cols-2 gap-px py-10 md:grid-cols-4">{[[PackageCheck,"Compra fácil","Selecciona y confirma por WhatsApp."],[Headphones,"Atención personal","Acompañamiento antes y después."],[Sparkles,"Selección cuidada","Productos elegidos con intención."],[ShieldCheck,"Compra segura","Tu información se maneja con cuidado."]].map(([Icon,title,copy]) => { const C = Icon as typeof PackageCheck; return <div key={String(title)} className="px-4 py-6 text-center"><C className="mx-auto text-[var(--gold)]" strokeWidth={1.25} /><h3 className="mt-4 text-sm font-bold">{String(title)}</h3><p className="muted mx-auto mt-2 max-w-[220px] text-xs leading-5">{String(copy)}</p></div>; })}</div></section></main>;
}
