import { getCategories } from "@/lib/data";
import { saveCategoryAction } from "@/app/admin/actions";
import { CategoryDelete } from "@/components/admin/category-delete";
import { CategoryEditor } from "@/components/admin/category-editor";

export default async function CategoriesPage() {
  const categories = await getCategories(true);
  return <><div><p className="eyebrow text-[var(--gold)]">Organización</p><h1 className="display mt-2 text-5xl">Categorías</h1><p className="muted mt-3 text-sm">Crea categorías y subcategorías sin modificar el código.</p></div><section className="mt-8 grid gap-6 xl:grid-cols-[360px_1fr]"><form action={saveCategoryAction} className="h-fit border hairline bg-[var(--paper)] p-5"><h2 className="display mb-5 text-3xl">Nueva categoría</h2><div className="grid gap-4"><div className="field"><label htmlFor="name">Nombre</label><input id="name" name="name" required className="input"/></div><div className="field"><label htmlFor="slug">URL opcional</label><input id="slug" name="slug" className="input" placeholder="Se genera del nombre"/></div><div className="field"><label htmlFor="description">Descripción</label><textarea id="description" name="description" className="input"/></div><div className="field"><label htmlFor="image_url">Imagen de portada</label><input id="image_url" name="image_url" className="input" placeholder="URL de imagen"/></div><div className="field"><label htmlFor="parent_id">Categoría principal</label><select id="parent_id" name="parent_id" className="input"><option value="">Ninguna</option>{categories.filter(c=>!c.parent_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label htmlFor="sort_order">Orden</label><input id="sort_order" name="sort_order" type="number" min="0" defaultValue="0" className="input"/></div><label className="flex items-center gap-3 text-sm"><input name="active" type="checkbox" defaultChecked/>Activa</label><button className="button-primary">Crear categoría</button></div></form><div className="overflow-x-auto border hairline bg-[var(--paper)]"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-[#e9e5dc] text-xs uppercase tracking-[.1em]"><tr><th className="p-4">Categoría</th><th className="p-4">URL</th><th className="p-4">Estado</th><th className="p-4 text-right">Acciones</th></tr></thead><tbody>{categories.map(c=><tr key={c.id} className="border-t hairline"><td className="p-4"><strong>{c.name}</strong>{c.description&&<p className="muted mt-1 max-w-sm text-xs">{c.description}</p>}</td><td className="p-4">/{c.slug}</td><td className="p-4"><span className={`pill ${c.active?"bg-[var(--success)]":"bg-[var(--muted)]"}`}>{c.active?"Activa":"Oculta"}</span></td><td className="p-4"><div className="flex justify-end"><CategoryEditor category={c} categories={categories}/><CategoryDelete id={c.id} name={c.name}/></div></td></tr>)}</tbody></table></div></section></>;
}
